### ISSUE TITLE
WordPress Error Protection reporting problems with acf pro 5.8.7

### ISSUE THREAD

**Issue by witpok** [AdvancedCustomFields/acf#261]
Hi,
After recent updates I'm receiving automatic emails with reports about acf pro 5.8.7 related errors. Everything seems to work fine (I will test sites thoroughly, but need time), but I think I should let you guys know. Wordpress 5.3.1, php 7.3.1, emails are created by this recently introduced in wordpress 5.2 automatic reporting.

===================
Error type E_ERROR on line 104 in file /home/.../public_html/.../wp-content/plugins/advanced-custom-fields-pro/acf.php. Error message: Uncaught Error: Call to undefined function acf_include() in /home/.../public_html/.../wp-content/plugins/advanced-custom-fields-pro/acf.php:104
Stack trace:
#0 /home/.../public_html/.../wp-content/plugins/advanced-custom-fields-pro/acf.php(609): ACF->initialize()
#1 /home/.../public_html/.../wp-content/plugins/advanced-custom-fields-pro/acf.php(615): acf()
#2 /home/.../public_html/.../wp-settings.php(360): include_once('/home/.../pu...')
#3 /home/.../public_html/.../wp-config.php(89): require_once('/home/.../pu...')
#4 /home/.../public_html/.../wp-load.php(37): require_once('/home/.../pu...')
#5 /home/.../public_html/.../wp-admin/admin-ajax.php(22): require_once('/home/.../pu...')
#6 {main}
  thrown 

If you need any more information, please let me know.

**Comment by elliotcondon** [comment]
Hi @witpok 

This error suggests that your site is missing (or unable to load) a required file within the ACF PRO plugin. 

The `acf_include()` function is defined within the "includes/acf-utility-functions.php" file. Please ensure this file exists, and that there are no file permissions preventing the file from being included.

**Comment by witpok** [comment]
@elliotcondon Hello Elliot, I'm sorry it took so long to verify your answer. I have experienced this error once again on another site. I have removed old plugin directory, extracted newest package from your main site (5.8.7) and uploaded in place of old plugin via ftp. Everything works well, but I have received same email with error report that acf_include() is undefined. File acf-utility-functions.php in inludes is present, function acf_include is defined, all file permissions are by default 644.

**Comment by elliotcondon** [comment]
@witpok - How strange!? In this case, I will need to encourage you to perform some manual debugging wto better understand why the `acf_include()` function is not defined.

Perhaps in some page loads, the `acf-utility-functions.php` file is not loaded?

I would start by adding some simple logging within the `acf-utility-functions.php` file (to check that the file exists and that the `acf_include()` function exists), and then another log where the original error stems from.
