### ISSUE TITLE
Options page values not loading with param 'option'

### ISSUE THREAD

**Issue by jensaxena** [AdvancedCustomFields/acf#413]
As of recently an existing template using the format `get_field('field_name', 'option')` fails to load content; var_dump returns 'NULL'. The template functions as expected after changing the parameter to 'options'.

Reference:

https://www.advancedcustomfields.com/resources/get-values-from-an-options-page/

> The $post_id parameter needed is a string containing the word ‘option’ or ‘options’.

Version:

ACF PRO 5.9.3
WordPress 5.5.3

**Comment by elliotcondon** [comment]
Thanks @jensaxena 

I'll test this out and will be in touch shortly.

**Comment by elliotcondon** [comment]
Hi again 👋. Just tested the issue, but was not able to replicate the problem. Both "option" and "options" correctly resolved to the "options" namespace.

Can you please try debugging the result of:
`
acf_get_valid_post_id( 'options' );
acf_get_valid_post_id( 'option' );
`

These should both return the string "options".

**Comment by jensaxena** [comment]
Apologies for the delayed response, results were 'options' and 'option'.

Test:
![code](https://user-images.githubusercontent.com/32103300/100903201-9c2d8d80-3493-11eb-9bc6-1ac016d70690.png)

Result:
![screenshot-localhost-2020 12 02-11_38_43](https://user-images.githubusercontent.com/32103300/100903245-a8b1e600-3493-11eb-8493-1cb84564f249.png)

**Comment by elliotcondon** [comment]
Hi @jensaxena 

Thanks for the reply. These results are different to what we would expect, which is a good thing that helps explain your original issue. Can you please perform some debugging within the `acf_get_valid_post_id()` function found in the file "includes/api/api-helpers.php" and check that the logic on line 2649 is running as intended?

**Comment by jensaxena** [comment]
Just setting up a proper debugger for this one, will get back to you shortly.

**Comment by jensaxena** [comment]
It appears that we're not actually getting to `acf_get_valid_post_id()` yet.

Output:
```
PHP Fatal error:  Uncaught Error: Call to undefined function apply_filters() in /wp-content/plugins/advanced-custom-fields-pro/includes/api/api-helpers.php:93
Stack trace:
#0 /wp-content/plugins/advanced-custom-fields-pro/includes/api/api-helpers.php(73): acf_validate_setting('php_to_js_date_...')
#1 /wp-content/plugins/advanced-custom-fields-pro/includes/api/api-helpers.php(2264): acf_update_setting('php_to_js_date_...', Array)
#2 {main}
  thrown in /wp-content/plugins/advanced-custom-fields-pro/includes/api/api-helpers.php on line 93
```

Unsuccessful troubleshooting steps:
Deactivate all other plugins
Manually reinstall WordPress core 5.5.3
Manually reinstall ACF Pro 5.9.3

Let me know if there are next steps or further information I could provide :)

**Comment by elliotcondon** [comment]
Hi @jensaxena. Thanks for the PHP error log. The issue here is a little worrying as it implies a core WP function `apply_filters()` does not exist. Can you please confirm that you are running your code within a theme file on the front end, or a WP action on the backend, and not a custom `.php` file running on the server?

**Comment by jensaxena** [comment]
Yes, it's a theme file under the standard WP directory structure.

**Comment by elliotcondon** [comment]
Hi @jensaxena. Without the `apply_filters()` function available, WordPress won't be able to load. There must be an explanation for why this function doesn't exist when attempting to debug the `acf_get_valid_post_id()` function on your site. Can you please add your `var_dump` debugging code to the functions.php file? This file will run on all page loads, after WordPress is correctly initialized.
